### ISSUE TITLE
2 Electron Windows open if setting the "--show" flag?

### ISSUE THREAD

**Issue by conanak99** [twolfson/karma-electron#28]
When I tried to set the --show flag in karma.conf.js, the launcher open 2 electron windows instead of 1.
(1 with Karma and 1 empty)

![image](https://user-images.githubusercontent.com/6670026/33168955-bec8a488-d07d-11e7-8360-f90cc8697790.png)

This is my karma.conf.js
```
    preprocessors: {
      '**/*.js': ['electron'],
      '**/*.spec.js': ['electron']
    },
    client: {
      useIframe: false
    },
    browsers: ['CustomElectron'],
    customLaunchers: {
      CustomElectron: {
        base: 'Electron',
        flags: ['--show']
      }
    }
```

If I remove the --show flag, the unit test is run headerless as expected.

**Comment by twolfson** [comment]
Sorry for the slow reply. This is the expected behavior; Karma operates on 2 contexts:

- A parent context which tracks how tests are runnning and reports those back to Node.js 
- A child context which runs the actual tests (e.g. sets up Mocha hooks, loads Mocha test suite)

Normally Karma loads the child context in an `iframe` of the parent context. However, we use `client.useIframe` which causes Karma to load the child context as a separate window. This is required due to security issues for iframes in Electron
