### ISSUE TITLE
tests in the main process

### ISSUE THREAD

**Issue by brcarey** [twolfson/karma-electron#5]
any thoughts on a config switch to run tests in the main process, instead of the renderer?

**Comment by twolfson** [comment]
Karma is built for testing in browsers, there's not really any way for it to run in the main process. If you are looking for a solution to run `mocha` or similar in an Electron application, then that can be done via a `require`:

**my-application/bin/mocha:**

``` js
// When we run into an uncaught exception, fail hard
// DEV: Without this line, Karma can hang indefinitely
process.on('uncaughtException', function handleUncaughtException (err) {
  throw err;
});

// Load in mocha executable (which will handle CLI parsing, etc)
// https://github.com/mochajs/mocha/blob/v2.4.5/package.json#L266-L267
require('mocha/bin/mocha');
```

To run the executable, we use `electron` instead of `node`:

``` bash
electron bin/mocha
# We can pass mocha flags as per usual
# electron bin/mocha test/sub-dir --recursive
```

This pattern should work similarly for any other testing framework.
